---
framework: jest
postMerge:
  pattern:
    - "./test/*.js"
preMerge:
  pattern:
    - "./test/*.js"
preRun:
     command:
        - yarn install --immutable
        - yarn run build
postRun:
     command:
        - yarn --version
        - echo 'done'
parallelism: 4
version: 1.0
