---
framework: jest
postMerge:
  pattern:
    - "./test/*.js"
  env: 
    NPM_TOKEN: test
preMerge:
  pattern:
    - "./test/*.js"
  env: 
    NPM_TOKEN: test
preRun:
     command:
        - yarn install --immutable
        - yarn run build
postRun:
     command:
        - yarn --version
version: 1.0
