---
framework: jest
postMerge:
  pattern:
    - "./test/*.js"
preMerge:
  pattern:
    - "./test/*.js"
preRun:
     command:
        - yarn install --immutable
        - yarn run build
postRun:
     command:
        - yarn --version
parallelism: 5
version: 1.0
